import 'package:daily_medicinebd/controllers/auth_controller.dart';
import 'package:daily_medicinebd/models/medicine_model.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'home_details.dart';

class HomeSchreen extends StatefulWidget {
  const HomeSchreen({super.key});

  @override
  State<HomeSchreen> createState() => _HomeSchreenState();
}

class _HomeSchreenState extends State<HomeSchreen> {
  final controller = Get.put(AuthController());

  final List<MedicineModel> medicineList = [
    MedicineModel(
      category: "FEVER / PAIN",
      medicineName: "Paracetamol",
      diseaseName: "Fever",
      overview: "The most common medicine for fever and mild pain.",
      symptoms: "• High temperature\n• Body ache",
      diagnosticTests: "• Thermometer check",
      dosageAdult: "500mg - 1000mg every 4-6 hours.",
      dosageChild: "10-15 mg/kg per dose.",
      sideEffects: "• Safe (Liver damage in high overdose)",
    ),
    MedicineModel(
      category: "FEVER / PAIN",
      medicineName: "Ibuprofen",
      diseaseName: "Headache / Pain",
      overview: "NSAID used for pain relief and reducing inflammation.",
      symptoms: "• Headache\n• Toothache",
      diagnosticTests: "• Physical Check",
      dosageAdult: "400mg every 6-8 hours after food.",
      dosageChild: "5-10 mg/kg.",
      sideEffects: "• Gastric irritation\n• Nausea",
    ),
    MedicineModel(
      category: "FEVER / PAIN",
      medicineName: "Paracetamol + Caffeine",
      diseaseName: "Migraine",
      overview: "Combination medicine specifically for migraine headaches.",
      symptoms: "• Severe one-sided headache\n• Sensitivity to light",
      diagnosticTests: "• Clinical assessment",
      dosageAdult: "2 tablets at onset of migraine.",
      dosageChild: "Not recommended.",
      sideEffects: "• Insomnia\n• Jitters",
    ),
    MedicineModel(
      category: "FEVER / PAIN",
      medicineName: "Aceclofenac",
      diseaseName: "Arthritis / Joint Pain",
      overview: "Relieves pain and inflammation in osteoarthritis and rheumatoid arthritis.",
      symptoms: "• Joint swelling\n• Stiffness",
      diagnosticTests: "• X-Ray",
      dosageAdult: "100mg twice daily.",
      dosageChild: "Not for children.",
      sideEffects: "• Indigestion\n• Dizziness",
    ),
    MedicineModel(
      category: "FEVER / PAIN",
      medicineName: "Diclofenac",
      diseaseName: "Muscle Pain",
      overview: "Strong painkiller for muscle injuries and back pain.",
      symptoms: "• Back pain\n• Muscle strain",
      diagnosticTests: "• MRI if severe",
      dosageAdult: "50mg 2-3 times daily after food.",
      dosageChild: "Consult doctor.",
      sideEffects: "• Stomach ulcer risk",
    ),

    MedicineModel(
      category: "COLD / COUGH",
      medicineName: "Phenylephrine",
      diseaseName: "Cold / Blocked Nose",
      overview: "Decongestant used to relieve nasal discomfort caused by colds.",
      symptoms: "• Stuffy nose\n• Sinus pressure",
      diagnosticTests: "• None",
      dosageAdult: "10mg every 4 hours.",
      dosageChild: "Consult doctor.",
      sideEffects: "• Nervousness\n• Sleep trouble",
    ),
    MedicineModel(
      category: "COLD / COUGH",
      medicineName: "Dextromethorphan",
      diseaseName: "Dry Cough",
      overview: "Cough suppressant used for dry, tickly coughs.",
      symptoms: "• Continuous coughing without mucus",
      diagnosticTests: "• Chest X-Ray (if chronic)",
      dosageAdult: "10-20mg every 4 hours.",
      dosageChild: "Syrup available.",
      sideEffects: "• Drowsiness\n• Dizziness",
    ),
    MedicineModel(
      category: "COLD / COUGH",
      medicineName: "Ambroxol + Guaifenesin",
      diseaseName: "Wet / Productive Cough",
      overview: "Helps thin and loosen mucus in the chest.",
      symptoms: "• Chest congestion\n• Cough with phlegm",
      diagnosticTests: "• Stethoscope check",
      dosageAdult: "10ml syrup 3 times daily.",
      dosageChild: "5ml syrup 2-3 times daily.",
      sideEffects: "• Nausea\n• Vomiting",
    ),
    MedicineModel(
      category: "ALLERGY",
      medicineName: "Chlorpheniramine",
      diseaseName: "Allergy / Sneezing",
      overview: "Older antihistamine, very effective but causes sleepiness.",
      symptoms: "• Runny nose\n• Sneezing",
      diagnosticTests: "• None",
      dosageAdult: "4mg every 4-6 hours.",
      dosageChild: "1mg-2mg based on age.",
      sideEffects: "• High drowsiness",
    ),
    MedicineModel(
      category: "ALLERGY",
      medicineName: "Loratadine",
      diseaseName: "Seasonal Allergy",
      overview: "Non-drowsy allergy relief.",
      symptoms: "• Hay fever\n• Itchy skin",
      diagnosticTests: "• Allergy test",
      dosageAdult: "10mg once daily.",
      dosageChild: "5mg syrup/tablet.",
      sideEffects: "• Headache",
    ),
    MedicineModel(
      category: "ALLERGY",
      medicineName: "Fexofenadine",
      diseaseName: "Chronic Allergy",
      overview: "Effective for long-term allergy management without sleepiness.",
      symptoms: "• Hives\n• Red eyes",
      diagnosticTests: "• IgE Blood test",
      dosageAdult: "120mg or 180mg daily.",
      dosageChild: "30mg twice daily (6-11 yrs).",
      sideEffects: "• Dry mouth",
    ),

    MedicineModel(
      category: "ASTHMA",
      medicineName: "Salbutamol",
      diseaseName: "Asthma Wheezing",
      overview: "Fast-acting inhaler/syrup to open airways.",
      symptoms: "• Wheezing\n• Tight chest",
      diagnosticTests: "• Spirometry",
      dosageAdult: "2 puffs every 4-6 hours.",
      dosageChild: "Syrup 2-4mg.",
      sideEffects: "• Shaking hands (tremor)\n• Fast heartbeat",
    ),
    MedicineModel(
      category: "ASTHMA",
      medicineName: "Budesonide",
      diseaseName: "Chronic Asthma",
      overview: "Steroid inhaler to prevent asthma attacks.",
      symptoms: "• Daily breathing difficulty",
      diagnosticTests: "• Lung function test",
      dosageAdult: "200-400mcg twice daily via inhaler.",
      dosageChild: "Lower dose via Nebulizer.",
      sideEffects: "• Oral thrush (rinse mouth after use)",
    ),
    MedicineModel(
      category: "ASTHMA",
      medicineName: "Montelukast",
      diseaseName: "Asthma + Allergy",
      overview: "Prevents asthma symptoms caused by allergies.",
      symptoms: "• Night-time cough\n• Allergy triggered asthma",
      diagnosticTests: "• None",
      dosageAdult: "10mg once evening.",
      dosageChild: "4mg or 5mg chewable.",
      sideEffects: "• Mood changes",
    ),

    MedicineModel(
      category: "GASTRIC",
      medicineName: "Omeprazole",
      diseaseName: "Gastritis",
      overview: "Reduces stomach acid.",
      symptoms: "• Burning stomach\n• Gas",
      diagnosticTests: "• Endoscopy",
      dosageAdult: "20mg before breakfast.",
      dosageChild: "Avoid.",
      sideEffects: "• Headache",
    ),
    MedicineModel(
      category: "GASTRIC",
      medicineName: "Pantoprazole",
      diseaseName: "Acid Reflux",
      overview: "Treats acid damage to the stomach and esophagus.",
      symptoms: "• Sour taste in mouth\n• Chest burn",
      diagnosticTests: "• Endoscopy",
      dosageAdult: "40mg daily before food.",
      dosageChild: "Not recommended.",
      sideEffects: "• Diarrhea",
    ),
    MedicineModel(
      category: "GASTRIC",
      medicineName: "Esomeprazole",
      diseaseName: "GERD / Ulcer",
      overview: "Stronger acid reducer for severe reflux.",
      symptoms: "• Severe heartburn\n• Difficulty swallowing",
      diagnosticTests: "• Stool H.Pylori",
      dosageAdult: "20mg or 40mg daily.",
      dosageChild: "Consult doctor.",
      sideEffects: "• Abdominal pain",
    ),
    MedicineModel(
      category: "GASTRIC",
      medicineName: "Domperidone",
      diseaseName: "Nausea / Gas",
      overview: "Helps stomach empty faster, stops vomiting.",
      symptoms: "• Bloating\n• Nausea",
      diagnosticTests: "• None",
      dosageAdult: "10mg before meals.",
      dosageChild: "Drops available.",
      sideEffects: "• Dry mouth",
    ),
    MedicineModel(
      category: "GASTRIC",
      medicineName: "Magaldrate + Simethicone",
      diseaseName: "Stomach Ache / Gas",
      overview: "Antacid syrup for instant relief.",
      symptoms: "• Stomach pain after eating",
      diagnosticTests: "• None",
      dosageAdult: "2 tsp after food.",
      dosageChild: "1 tsp.",
      sideEffects: "• Loose motion",
    ),
    MedicineModel(
      category: "GASTRIC",
      medicineName: "Dicycloverine",
      diseaseName: "IBS / Stomach Cramps",
      overview: "Relieves muscle spasms in the gut.",
      symptoms: "• Sharp stomach cramps (IBS)",
      diagnosticTests: "• Ultrasound",
      dosageAdult: "10-20mg tablet.",
      dosageChild: "Syrup available.",
      sideEffects: "• Dry mouth\n• Blurred vision",
    ),

    MedicineModel(
      category: "CONSTIPATION",
      medicineName: "Bisacodyl",
      diseaseName: "Chronic Constipation",
      overview: "Stimulant laxative to help bowel movement.",
      symptoms: "• Hard stool\n• No bowel movement > 3 days",
      diagnosticTests: "• None",
      dosageAdult: "5-10mg at night.",
      dosageChild: "Not recommended.",
      sideEffects: "• Stomach cramps",
    ),
    MedicineModel(
      category: "CONSTIPATION",
      medicineName: "Liquid Paraffin",
      diseaseName: "Hard Stool",
      overview: "Lubricant laxative.",
      symptoms: "• Painful stool",
      diagnosticTests: "• None",
      dosageAdult: "1-2 tablespoons at night.",
      dosageChild: "Consult doctor.",
      sideEffects: "• Anal leakage",
    ),
    MedicineModel(
      category: "DIARRHEA",
      medicineName: "ORS",
      diseaseName: "Dehydration",
      overview: "Replaces lost fluids and salts.",
      symptoms: "• Thirst\n• Dry skin\n• Weakness",
      diagnosticTests: "• Skin turgor",
      dosageAdult: "Drink after every loose stool.",
      dosageChild: "Sip frequently.",
      sideEffects: "• None",
    ),
    MedicineModel(
      category: "DIARRHEA",
      medicineName: "Loperamide",
      diseaseName: "Acute Diarrhea",
      overview: "Slows down gut movement to stop loose motion.",
      symptoms: "• Watery stool",
      diagnosticTests: "• Stool Routine",
      dosageAdult: "2 tablets first, then 1 after each motion.",
      dosageChild: "AVOID in children.",
      sideEffects: "• Constipation",
    ),
    MedicineModel(
      category: "DIARRHEA",
      medicineName: "Metronidazole",
      diseaseName: "Dysentery",
      overview: "Antibiotic for amoebic infections (blood/mucus in stool).",
      symptoms: "• Stomach pain\n• Mucus in stool",
      diagnosticTests: "• Stool Microscopy",
      dosageAdult: "400mg 3 times daily for 5 days.",
      dosageChild: "Syrup based on weight.",
      sideEffects: "• Metallic taste\n• Nausea",
    ),
    MedicineModel(
      category: "LIVER",
      medicineName: "Silymarin",
      diseaseName: "Fatty Liver",
      overview: "Herbal supplement to support liver health.",
      symptoms: "• Right side abdominal pain\n• Fatigue",
      diagnosticTests: "• SGPT/SGOT (Liver Function)",
      dosageAdult: "140mg 2-3 times daily.",
      dosageChild: "Not for children.",
      sideEffects: "• Mild laxative effect",
    ),
    MedicineModel(
      category: "LIVER",
      medicineName: "Ursodeoxycholic Acid",
      diseaseName: "Jaundice / Gallstones",
      overview: "Dissolves small gallstones and helps bile flow.",
      symptoms: "• Yellow eyes\n• Itchy skin",
      diagnosticTests: "• Bilirubin test",
      dosageAdult: "150-300mg twice daily.",
      dosageChild: "Specialist only.",
      sideEffects: "• Diarrhea",
    ),

    MedicineModel(
      category: "NERVOUS SYSTEM",
      medicineName: "Vitamin B1+B6+B12",
      diseaseName: "Neuropathy",
      overview: "Neuro-bion supplement for nerve health.",
      symptoms: "• Tinging\n• Burning sensation in feet",
      diagnosticTests: "• Clinical check",
      dosageAdult: "1 tablet daily.",
      dosageChild: "Not usually needed.",
      sideEffects: "• None",
    ),
    MedicineModel(
      category: "VITAMINS",
      medicineName: "Vitamin C",
      diseaseName: "Immunity",
      overview: "Antioxidant for skin and immunity.",
      symptoms: "• Weakness\n• Bleeding gums",
      diagnosticTests: "• None",
      dosageAdult: "500mg daily.",
      dosageChild: "250mg.",
      sideEffects: "• Gastric acidity",
    ),
    MedicineModel(
      category: "VITAMINS",
      medicineName: "Calcium + D3",
      diseaseName: "Bone Health",
      overview: "Prevents bone loss.",
      symptoms: "• Back pain",
      diagnosticTests: "• Vitamin D level",
      dosageAdult: "1 tablet daily.",
      dosageChild: "Syrup.",
      sideEffects: "• Gas",
    ),

    MedicineModel(
      category: "DIABETES",
      medicineName: "Metformin",
      diseaseName: "Type 2 Diabetes",
      overview: "Lowers blood sugar.",
      symptoms: "• High sugar levels",
      diagnosticTests: "• HbA1c",
      dosageAdult: "500mg - 1000mg with food.",
      dosageChild: "Specialist only.",
      sideEffects: "• Gas\n• Weight loss",
    ),
    MedicineModel(
      category: "DIABETES",
      medicineName: "Glimepiride",
      diseaseName: "Diabetes Control",
      overview: "Stimulates insulin release.",
      symptoms: "• Uncontrolled sugar",
      diagnosticTests: "• FBS",
      dosageAdult: "1mg - 2mg before breakfast.",
      dosageChild: "No.",
      sideEffects: "• Low blood sugar (Hypoglycemia)",
    ),
    MedicineModel(
      category: "BLOOD PRESSURE",
      medicineName: "Amlodipine",
      diseaseName: "High BP",
      overview: "Relaxes blood vessels.",
      symptoms: "• High BP reading",
      diagnosticTests: "• BP Check",
      dosageAdult: "5mg daily.",
      dosageChild: "No.",
      sideEffects: "• Swollen ankles",
    ),
    MedicineModel(
      category: "BLOOD PRESSURE",
      medicineName: "Losartan",
      diseaseName: "Hypertension",
      overview: "Protects kidneys in BP patients.",
      symptoms: "• High BP",
      diagnosticTests: "• Creatinine",
      dosageAdult: "50mg daily.",
      dosageChild: "No.",
      sideEffects: "• Dizziness",
    ),
    MedicineModel(
      category: "HEART",
      medicineName: "Furosemide",
      diseaseName: "Fluid Retention / Heart Failure",
      overview: "Diuretic (Water pill) to remove excess water.",
      symptoms: "• Swollen legs\n• Breathlessness",
      diagnosticTests: "• Electrolytes",
      dosageAdult: "40mg morning.",
      dosageChild: "Specialist.",
      sideEffects: "• Frequent urination\n• Weakness",
    ),

    MedicineModel(
      category: "WOMEN",
      medicineName: "Norethisterone",
      diseaseName: "Irregular Period",
      overview: "Hormone to regulate periods.",
      symptoms: "• Delayed period\n• Heavy bleeding",
      diagnosticTests: "• Ultrasound",
      dosageAdult: "5mg 2-3 times daily.",
      dosageChild: "No.",
      sideEffects: "• Nausea",
    ),
    MedicineModel(
      category: "WOMEN",
      medicineName: "Tranexamic Acid",
      diseaseName: "Heavy Bleeding",
      overview: "Stops excessive bleeding.",
      symptoms: "• Heavy menstrual flow",
      diagnosticTests: "• Hb%",
      dosageAdult: "500mg 3 times daily.",
      dosageChild: "No.",
      sideEffects: "• Stomach pain",
    ),
    MedicineModel(
      category: "WOMEN",
      medicineName: "Mefenamic Acid",
      diseaseName: "Period Pain",
      overview: "Painkiller specifically for menstrual cramps.",
      symptoms: "• Painful cramps",
      diagnosticTests: "• None",
      dosageAdult: "500mg 3 times daily.",
      dosageChild: "No.",
      sideEffects: "• Acidity",
    ),
    MedicineModel(
      category: "WOMEN",
      medicineName: "Folic Acid",
      diseaseName: "Pregnancy / Anemia",
      overview: "Essential for fetal development.",
      symptoms: "• Weakness",
      diagnosticTests: "• CBC",
      dosageAdult: "5mg daily.",
      dosageChild: "Safe.",
      sideEffects: "• None",
    ),

    MedicineModel(
      category: "KIDNEY",
      medicineName: "Ciprofloxacin",
      diseaseName: "UTI",
      overview: "Antibiotic for urine infection.",
      symptoms: "• Burning urine",
      diagnosticTests: "• Urine Culture",
      dosageAdult: "500mg twice daily.",
      dosageChild: "Specialist.",
      sideEffects: "• Nausea",
    ),
    MedicineModel(
      category: "KIDNEY",
      medicineName: "Nitrofurantoin",
      diseaseName: "Severe UTI",
      overview: "Antibiotic for bladder infection.",
      symptoms: "• Frequent urination",
      diagnosticTests: "• Urine R/E",
      dosageAdult: "100mg twice daily.",
      dosageChild: "Dose by weight.",
      sideEffects: "• Brown urine",
    ),
    MedicineModel(
      category: "KIDNEY",
      medicineName: "Potassium Citrate",
      diseaseName: "Kidney Stones",
      overview: "Prevents stone formation.",
      symptoms: "• Flank pain",
      diagnosticTests: "• Ultrasound KUB",
      dosageAdult: "1-2 tablets 3 times daily.",
      dosageChild: "No.",
      sideEffects: "• Stomach upset",
    ),
    MedicineModel(
      category: "KIDNEY",
      medicineName: "Tamsulosin",
      diseaseName: "Urinary Retention",
      overview: "Helps flow of urine in prostate issues.",
      symptoms: "• Weak stream",
      diagnosticTests: "• PSA",
      dosageAdult: "0.4mg daily.",
      dosageChild: "No.",
      sideEffects: "• Dizziness",
    ),

    MedicineModel(
      category: "SKIN",
      medicineName: "Permethrin",
      diseaseName: "Scabies",
      overview: "Cream to kill skin mites.",
      symptoms: "• Intense itching",
      diagnosticTests: "• None",
      dosageAdult: "Apply neck down overnight.",
      dosageChild: "Safe.",
      sideEffects: "• Itching",
    ),
    MedicineModel(
      category: "SKIN",
      medicineName: "Clotrimazole",
      diseaseName: "Fungal Infection",
      overview: "Antifungal cream.",
      symptoms: "• Ringworm\n• Itchy toes",
      diagnosticTests: "• None",
      dosageAdult: "Apply twice daily.",
      dosageChild: "Safe.",
      sideEffects: "• Burning",
    ),
    MedicineModel(
      category: "SKIN",
      medicineName: "Betamethasone",
      diseaseName: "Eczema / Inflammation",
      overview: "Steroid cream for redness and swelling.",
      symptoms: "• Red itchy patches",
      diagnosticTests: "• None",
      dosageAdult: "Apply thinly twice daily.",
      dosageChild: "Use cautiously.",
      sideEffects: "• Thinning skin",
    ),
    MedicineModel(
      category: "SKIN",
      medicineName: "Hydrocortisone",
      diseaseName: "Mild Allergy",
      overview: "Mild steroid for insect bites/rash.",
      symptoms: "• Itchy bumps",
      diagnosticTests: "• None",
      dosageAdult: "Apply twice daily.",
      dosageChild: "Safe.",
      sideEffects: "• None usually",
    ),

    MedicineModel(
      category: "EYE",
      medicineName: "Ketotifen",
      diseaseName: "Eye Allergy",
      overview: "Drops for itchy eyes.",
      symptoms: "• Itching",
      diagnosticTests: "• None",
      dosageAdult: "1 drop twice daily.",
      dosageChild: "Safe.",
      sideEffects: "• Stinging",
    ),
    MedicineModel(
      category: "EYE",
      medicineName: "Artificial Tears",
      diseaseName: "Dry Eyes",
      overview: "Lubricating drops.",
      symptoms: "• Gritty sensation",
      diagnosticTests: "• None",
      dosageAdult: "As needed.",
      dosageChild: "Safe.",
      sideEffects: "• None",
    ),
    MedicineModel(
      category: "EYE",
      medicineName: "Ciprofloxacin Eye Drop",
      diseaseName: "Eye Infection",
      overview: "Antibiotic drop.",
      symptoms: "• Redness with pus",
      diagnosticTests: "• None",
      dosageAdult: "1 drop every 4 hours.",
      dosageChild: "Safe.",
      sideEffects: "• Stinging",
    ),
    MedicineModel(
      category: "ENT",
      medicineName: "Xylometazoline",
      diseaseName: "Nasal Block",
      overview: "Nasal spray decongestant.",
      symptoms: "• Blocked nose",
      diagnosticTests: "• None",
      dosageAdult: "1 spray twice daily (Max 5 days).",
      dosageChild: "Pediatric drops.",
      sideEffects: "• Dry nose",
    ),

    MedicineModel(
      category: "MENTAL",
      medicineName: "Lorazepam",
      diseaseName: "Anxiety",
      overview: "Calms the brain.",
      symptoms: "• Panic\n• Restlessness",
      diagnosticTests: "• Clinical",
      dosageAdult: "1mg daily (Prescription only).",
      dosageChild: "No.",
      sideEffects: "• Sleepiness\n• Addiction risk",
    ),
    MedicineModel(
      category: "MENTAL",
      medicineName: "Diazepam",
      diseaseName: "Sleep / Seizure",
      overview: "Muscle relaxant and sedative.",
      symptoms: "• Insomnia",
      diagnosticTests: "• None",
      dosageAdult: "5-10mg at night.",
      dosageChild: "Specialist.",
      sideEffects: "• Drowsiness",
    ),

    MedicineModel(
      category: "THYROID",
      medicineName: "Levothyroxine",
      diseaseName: "Hypothyroidism",
      overview: "Replaces missing thyroid hormone.",
      symptoms: "• Weight gain\n• Cold feeling",
      diagnosticTests: "• TSH, T3, T4",
      dosageAdult: "Empty stomach morning (Dose varies).",
      dosageChild: "Specialist.",
      sideEffects: "• Palpitations",
    ),
    MedicineModel(
      category: "THYROID",
      medicineName: "Carbimazole",
      diseaseName: "Hyperthyroidism",
      overview: "Reduces thyroid hormone production.",
      symptoms: "• Weight loss\n• Shaking",
      diagnosticTests: "• TSH",
      dosageAdult: "5-20mg daily.",
      dosageChild: "Specialist.",
      sideEffects: "• Rash",
    ),

    MedicineModel(
      category: "SYSTEMIC",
      medicineName: "Prednisolone",
      diseaseName: "Severe Inflammation",
      overview: "Steroid for asthma, arthritis, autoimmunity.",
      symptoms: "• Swelling\n• Allergies",
      diagnosticTests: "• None",
      dosageAdult: "5mg - 20mg (After food).",
      dosageChild: "Dose by weight.",
      sideEffects: "• Weight gain\n• Gastritis",
    ),
    MedicineModel(
      category: "FUNGAL",
      medicineName: "Fluconazole",
      diseaseName: "Systemic Fungal Infection",
      overview: "Oral antifungal tablet.",
      symptoms: "• Yeast infection",
      diagnosticTests: "• None",
      dosageAdult: "150mg single dose (usually).",
      dosageChild: "Specialist.",
      sideEffects: "• Nausea",
    ),
  ];

  @override
  void initState() {
    super.initState();
    controller.filteredList.value = medicineList;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        titleSpacing: 0,
        title: Container(
          height: 45,
          width: Get.width,
          decoration: const BoxDecoration(
            color: Colors.red,
          ),
          child: TextField(

            onChanged: (value) => controller.runFilter(value, medicineList),
            style: const TextStyle(color: Colors.white),
            cursorColor: Colors.white,
            decoration: const InputDecoration(
              hintText: 'Search Disease or Medicine...',
              hintStyle: TextStyle(color: Colors.white70),
              prefixIcon: Icon(Icons.search, color: Colors.white),
              border: InputBorder.none,
              contentPadding: EdgeInsets.only(top: 8),
            ),
          ),
        ),
      ),
      backgroundColor: Colors.white,

      body: Obx(
            () => ListView.builder(
          itemCount: controller.filteredList.length,
          padding: const EdgeInsets.all(10),
          itemBuilder: (context, index) {
            final data = controller.filteredList[index];
            return Padding(
              padding: const EdgeInsets.symmetric(vertical: 5),
              child: Card(
                elevation: 3,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                child: ListTile(
                  contentPadding: const EdgeInsets.all(12),
                  leading: CircleAvatar(
                    backgroundColor: Colors.redAccent.withOpacity(0.2),
                    child: const Icon(Icons.medical_services, color: Colors.red),
                  ),
                  title: Text(
                    data.medicineName,
                    style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
                  ),
                  subtitle: Text(
                    "${data.category} - ${data.diseaseName}",
                    style: TextStyle(color: Colors.grey[700]),
                  ),
                  trailing: const Icon(Icons.arrow_forward_ios, size: 16),


                  onTap: () {
                    Get.to(() => const HomeDetails(), arguments: data);
                  },
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}